apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organization-api
  template:
    metadata:
      labels:
        app: organization-api
    spec:
      containers:
      - name: organization-api
        image: jilsanregistries.azurecr.io/orgapi:<<BuildNumber>>
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: organization-api
spec:
  type: LoadBalancer
  ports:
  - port: 8081
  selector:
    app: organization-api